//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedOfficeWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.ArAps = new HashSet<ArAp>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string ZipCode { get; set; }
    
        public virtual ICollection<ArAp> ArAps { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
