//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedOfficeWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Patients = new HashSet<Patient>();
            this.ArAps = new HashSet<ArAp>();
        }
    
        public int EmployeeId { get; set; }
        public int EmployeeTypeId { get; set; }
        public int BranchId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<ArAp> ArAps { get; set; }
    }
}
