//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedOfficeWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseType
    {
        public ExpenseType()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int ExpenseTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
    }
}
