//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedOfficeWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public Insurance()
        {
            this.Patients = new HashSet<Patient>();
            this.ArAps = new HashSet<ArAp>();
        }
    
        public int InsuranceID { get; set; }
        public string Name { get; set; }
        public string InsuranceType { get; set; }
        public string InsuranceWebSite { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<ArAp> ArAps { get; set; }
    }
}
