//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedOfficeWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.ArAps = new HashSet<ArAp>();
        }
    
        public int ChartNumber { get; set; }
        public int EmployeeID { get; set; }
        public int InsuranceID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual ICollection<ArAp> ArAps { get; set; }
    }
}
